In [1]:
print("Hello")


Hello


In [2]:
a=([[1,2],[3,4]])
print(a)

[[1, 2], [3, 4]]


In [7]:
b = np.array(a)
print(b)

[[1 2]
 [3 4]]


In [6]:
import numpy as np


In [8]:
b.ndim


2

In [9]:
b.shape

(2, 2)

In [10]:
b.size

4

In [11]:
b.itemsize

4

In [12]:
b.dtype

dtype('int32')

In [13]:
b.data

In [14]:
c=[[[1,2],[3,4],[5,6]]]
print(c)


[[[1, 2], [3, 4], [5, 6]]]


In [15]:
d=np.array(c)
print(d)

[[[1 2]
  [3 4]
  [5 6]]]


In [16]:
d.ndim

3

In [18]:
np.zeros([200,400])

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [19]:
np.zeros(d.shape)

array([[[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [20]:
np.full([2,3],2)

array([[2, 2, 2],
       [2, 2, 2]])

In [21]:
np.random.rand(3,5)

array([[0.11758649, 0.51169573, 0.10216107, 0.5162076 , 0.15475723],
       [0.9993215 , 0.21692552, 0.86685311, 0.49185384, 0.83789261],
       [0.99827215, 0.42004891, 0.4857195 , 0.07417191, 0.13882361]])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
#copy array
e=np.copy(d)
print(e)

[[[1 2]
  [3 4]
  [5 6]]]


In [28]:
#sorting
d.sort()
print(d)

[[[1 2]
  [3 4]
  [5 6]]]


In [31]:
d.sort(axis=1)
print(d)

[[[1 2]
  [3 4]
  [5 6]]]


In [45]:
#reshape array
z=d.reshape(2,3)
print(z)

[[1 2 3]
 [4 5 6]]


In [48]:
#adding element
n=np.append(d,[7,8])
print(n)

[1 2 3 4 5 6 7 8]


In [59]:
#view
d.view(dtype='float32')

array([[[1.e-45, 3.e-45],
        [4.e-45, 6.e-45],
        [7.e-45, 8.e-45]]], dtype=float32)

In [49]:
#insert of element in array
q=np.insert(d,4,7)
print(q)

[1 2 3 4 7 5 6]


In [53]:
#delete element in array
print(d)
j=np.delete(d,2,axis=1)
print(j)

[[[1 2]
  [3 4]
  [5 6]]]
[[[1 2]
  [3 4]]]


In [57]:
#concetenate array in two array
a1=[[10,30,20],[50,40,60]]
a2=[[2,5,6,],[8,9,7]]
z=np.concatenate((a1,a2),axis=0)
print(z)

[[10 30 20]
 [50 40 60]
 [ 2  5  6]
 [ 8  9  7]]


In [64]:
#split in array
a3=[1,2,3,4,5,6,7,8,9,0]
a4=np.array(a3)
print(a4)
g=np.split(a4,5)
print(g)

[1 2 3 4 5 6 7 8 9 0]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([9, 0])]


In [66]:
#indexing array
a5=a4[2]
print(a5)

3


In [67]:
#indexing
a4[1]

2

In [75]:
#slicing
#[start:stop:step]
a4[3:5]

array([4, 5])

In [76]:
a4[:2]

array([1, 2])

In [80]:
a4[0:9:2]

array([1, 3, 5, 7, 9])

In [89]:
print(b)
b[:,1]

[[1 2]
 [3 4]]


array([2, 4])

In [91]:
print(d)
d[:,1]

[[[1 2]
  [3 4]
  [5 6]]]


array([[3, 4]])

In [12]:
import numpy as np




In [13]:
#addition 
a1=10
a2=20
sum=np.add(a1,a2)
print(sum)

30


In [15]:
#substraction
sub=np.subtract(a1,a2)
print(sub)

-10


In [16]:
#multiplication
mul=np.multiply(a1,a2)
print(mul)

200


In [17]:
#division
div=np.divide(a1,a2)
print(div)

0.5


In [18]:
#exponentiation
w=np.exp(a1)
print(w)

22026.465794806718


In [20]:
#square root
sq=np.sqrt(a1)
print(sq)

3.1622776601683795


In [21]:
#comparison
a1==a2

False

In [25]:
#sum of array
arr=[10,20,30,40]
s1=np.array(arr)
s1.sum()

100

In [26]:
#min value find in array
s1.min()

10

In [27]:
#max value find in array
s1.max()

40

In [32]:
#find median (Average)
s1.mean()

25.0

In [35]:
print(s1)
s1.mode()

[10 20 30 40]
